package project;

public class Report {
    private String title;
    private String content;
    private String generatedDate;
    private String generatedBy;

    /**
     * Constructs a new Report with specified parameters.
     * 
     * @param title The title of the report
     * @param content The content of the report
     * @param generatedBy The user who generated the report
     */
    public Report(String title, String content, String generatedBy) {
        this.title = title;
        this.content = content;
        this.generatedDate = java.time.LocalDate.now().toString();
        this.generatedBy = generatedBy;
    }

    // Getters
    public String getTitle() {
        return title;
    }

    public String getContent() {
        return content;
    }

    public String getGeneratedDate() {
        return generatedDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    @Override
    public String toString() {
        return "Report: " + title + "\nGenerated on: " + generatedDate + 
               "\nGenerated by: " + generatedBy + "\n\nContent:\n" + content;
    }
}
